=== arturosa67/XML_Definir_trayectorias_Robot/fic_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- Definition of simple elements -->

<xs:element name="TOPOINT">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="xyz" use="required"/>
    <xs:attribute ref="angles" use="required"/>
    <xs:attribute ref="angles_type" use="required"/>
  </xs:complexType>
</xs:element> 
<xs:element name="LINE">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="xyz2" use="required"/>
    <xs:attribute ref="angles2" use="required"/>
    <xs:attribute ref="angles_type" use="required"/>
  </xs:complexType>
</xs:element> 
<xs:element name="ARC">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="xyz2" use="required"/>
    <xs:attribute ref="angles2" use="required"/>
    <xs:attribute ref="xyz3" use="required"/>
    <xs:attribute ref="angles3" use="required"/>
    <xs:attribute ref="angles_type" use="required"/>
  </xs:complexType>
</xs:element> 
<xs:element name="TOOL">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="velocity"/>
    <xs:attribute ref="time"/>
    <xs:attribute ref="active" use="required"/>
    <xs:attribute ref="acel"/>
  </xs:complexType>
</xs:element>





<!--Definition of types-->

  <xs:simpleType name="name_format">
   <xs:restriction base="xs:string">
   <xs:pattern value="[a-zA-Z_ 0-9]*"/>
   </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="point_format">
      <xs:restriction base="xs:string">
      <xs:pattern value="[\-0-9]*(\.)?[0-9]*[:][\-0-9]*(\.)?[0-9]*[:][-0-9]*(\.)?[0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="angle_format">
    <xs:restriction base="xs:string">
      <xs:pattern value="[-0-9]*(\.)?[0-9]*[:][-0-9]*(\.)?[0-9]*[:][-0-9]*(\.)?[0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

<xs:simpleType name="angle_type_format">
  <xs:restriction base="xs:string">
    <xs:enumeration value="ZYZ"/>
    <xs:enumeration value="ZXZ"/>
    <xs:enumeration value="RPY"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="number_format">
      <xs:restriction base="xs:string">
      <xs:pattern value="[-0-9]*(\.)?[0-9]*"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="active_format">
  <xs:restriction base="xs:string">
    <xs:enumeration value="ON"/>
    <xs:enumeration value="OFF"/>
  </xs:restriction>
</xs:simpleType>
<xs:simpleType name="HM_format">
      <xs:restriction base="xs:string">
      <!--<xs:pattern value="\[[-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[;][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[;][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[;][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*[ ][-0-9]*(\.)?[0-9]*\]"/>-->
      <xs:pattern value="\[(([-0-9]*(\.)?[0-9]*[ ]){3}[-0-9]*(\.)?[0-9]*[;]){3}([-0-9]*(\.)?[0-9]*[ ]){3}[-0-9]*(\.)?[0-9]*\]"/>
    </xs:restriction>
  </xs:simpleType>


<xs:simpleType name="units_format">
  <xs:restriction base="xs:string">
    <xs:enumeration value="mm:rad:s"/>
    <xs:enumeration value="m:gr:s"/>
  </xs:restriction>
</xs:simpleType>




<!-- Definition of attributes -->
 
<xs:attribute name="name"  type="name_format" default="__name__"/>
<xs:attribute name="xyz" type="point_format" default="0.0:0.0:0.0"/>
<xs:attribute name="angles" type="angle_format" default="0.0:0.0:0.0"/>
<xs:attribute name="xyz2" type="point_format" default="0.0:0.0:0.0"/>
<xs:attribute name="angles2" type="angle_format" default="0.0:0.0:0.0"/>
<xs:attribute name="xyz3" type="point_format" default="0.0:0.0:0.0"/>
<xs:attribute name="angles3" type="angle_format" default="0.0:0.0:0.0"/>
<xs:attribute name="angles_type" type="angle_type_format" default="ZYZ"/> <!--tipo de orientacion de angulos Euler -->
<xs:attribute name="velocity" type="number_format" default="0.0"/>
<xs:attribute name="time" type="number_format" default="0.0"/>
<xs:attribute name="active" type="active_format" default="OFF"/>
<xs:attribute name="acel" type="number_format" default="0.0"/>
<xs:attribute name="process_type" type="xs:string"/>
<xs:attribute name="units" type="units_format"/>
<xs:attribute name="file" type="xs:string"/>
<xs:attribute name="group" type="xs:string"/>
<xs:attribute name="HM_from_WORLD_to_SITE" type="HM_format" default="[1.0 0.0 0.0 0.0;0.0 1.0 0.0 0.0;0.0 0.0 1.0 0.0;0.0 0.0 0.0 1.0]"/>
<xs:attribute name="HM_from_SITE_to_PART" type="HM_format" default="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]"/>
<xs:attribute name="OVERWRITE_HM_from_SITE_to_PART" type="HM_format" default="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]"/>

<!-- Definicion de complex elements-->

<xs:element name="INCLUDE">
  <xs:complexType>
    <xs:attribute ref="name" use="required"/>
    <xs:attribute ref="file" use="required"/>
    <xs:attribute ref="group" use="required"/>
    <xs:attribute ref="OVERWRITE_HM_from_SITE_to_PART"/> <!--se puede poner o no-->
  </xs:complexType>
</xs:element> 
<xs:element name="GROUP">
	<xs:complexType>
	<xs:choice minOccurs="1" maxOccurs="unbounded">
		<xs:element ref="LINE" maxOccurs="unbounded"/>
		<xs:element ref="TOPOINT" maxOccurs="unbounded"/>
		<xs:element ref="ARC" maxOccurs="unbounded"/>
		<xs:element ref="TOOL" maxOccurs="unbounded"/>
		<xs:element ref="POLILINE" maxOccurs="unbounded"/>
		<xs:element ref="POLICURVE" maxOccurs="unbounded"/>
	</xs:choice>
		<xs:attribute ref="name" use="required"/>
    <xs:attribute ref="HM_from_SITE_to_PART"/>
	</xs:complexType>
</xs:element>
  <xs:element name="PROCESS">
  <xs:complexType>
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
       <xs:element ref="GROUP" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="INCLUDE" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
   <xs:attribute ref="process_type" use="required"/>
   <xs:attribute ref="units" use="required"/>
   <xs:attribute ref="HM_from_WORLD_to_SITE" use="required"/>
  </xs:complexType>
</xs:element> 
 
 <xs:element name="POLILINE">
  <xs:complexType>
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element ref="LINE" maxOccurs="unbounded"/>
    </xs:sequence>
  <xs:attribute ref="name" use="required"/>
</xs:complexType> 
</xs:element>

 <xs:element name="POLICURVE">
  <xs:complexType>
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element ref="ARC" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element ref="LINE" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="POLILINE" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  <xs:attribute ref="name" use="required"/>
</xs:complexType> 
</xs:element>


</xs:schema>

=== arturosa67/XML_Definir_trayectorias_Robot/pruebas/pieza1_welding.xml
<?xml version="1.0" encoding="UTF-8"?>
<PROCESS type="welding MIG/MAG" units="mm:rad:s" HM_from_WORLD_to_SITE="[1 0 0 1000;0 1 0 0;0 0 1 0;0 0 0 1]" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="fic_XSD.xsd">
<!--Part1 . Welding. -->
<GROUP name="Pieza1_Welding" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 0;0 0 1 500;0 0 0 1]">
<TOPOINT name="1" xyz="60:0:100 " angles="0:3.1416:0" angles_type="ZYZ"/>
<LINE name="2" xyz2="70:0:30" angles2="0:2.35:0" angles_type="ZYZ"/>
<LINE name="3" xyz2="70:400:30" angles2="0:2.35:0" angles_type="ZYZ"/>
<TOPOINT name="4" xyz="70:400:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="5" xyz="100:430:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<LINE name="6" xyz2="100:400:30" angles2="0:-2.35:0" angles_type="ZYZ"/>
<LINE name="7" xyz2="100:0:30" angles2="0:-2.35:0" angles_type="ZYZ"/>
<TOPOINT name="8" xyz="110:0:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="9" xyz="179.96:0:0 " angles="0:3.1416:0" angles_type="ZYZ"/>
<LINE name="10" xyz2="179.96:400:0" angles2="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="11" xyz="179.96:400:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="12" xyz="260:0:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<LINE name="13" xyz2="270:0:30" angles2="0:2.35:0" angles_type="ZYZ"/>
<LINE name="14" xyz2="270:400:30" angles2="0:2.35:0" angles_type="ZYZ"/>
<TOPOINT name="15" xyz="260:400:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="16" xyz="310:0:225 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="17" xyz="340:0:225 " angles="0:3.416:0" angles_type="ZYZ"/>
<LINE name="18" xyz2="380:0:30" angles2="0:2.5:0" angles_type="ZYZ"/>
<LINE name="19" xyz2="380:350:30" angles2="0:2.5:0" angles_type="ZYZ"/>
<LINE name="20" xyz2="380:350:200" angles2="0:2.5:0" angles_type="ZYZ"/>
<TOPOINT name="21" xyz="200:200:225 " angles="0:3.416:0" angles_type="ZYZ"/>
</GROUP>
</PROCESS>

=== arturosa67/XML_Definir_trayectorias_Robot/fic_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<PROCESS process_type="welding MIG/MAG" units="mm:rad:s" HM_from_WORLD_to_SITE="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="fic_XSD.xsd">

<!--esto es un comentario y se ignoran -->

<GROUP name="G1" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]">

<TOPOINT name="G1_punto_inicial" xyz="1.9:50.0:10.7" angles="0:1.57:0" angles_type="ZYZ"/>
<TOOL name="G1_activo_soldadura" velocity="1.2" time="0" active="ON"/>
<LINE name="G1_linea_de_soldadura" xyz2="200:50:10" angles2="0:1.57:0" angles_type="ZYZ"/>

<ARC name="G1_arco_de_soldadura" xyz2="180:0:10" angles2="0:1.57:0" xyz3="100:-50:10" angles3="0:1.57:0" angles_type="ZYZ"/>
<TOOL name="G1_desactivo_soldadura" velocity="1.3" active="OFF"/>
<TOPOINT name="G1_punto_reposo" xyz="0:0:50" angles="0:1.57:0" angles_type="ZYZ"/>
<
</GROUP>

<INCLUDE name="nueva pieza" file="./pepe.xml" group="G3" OVERWRITE_HM_from_SITE_to_PART="[0.0 0.0 1.0 0.0;0.0 1.0 0.0 0.0;1.0 0.0 0.0 10.0;0 0 0 1]"/>

<GROUP name="G2" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]">

<TOPOINT name="G2_aproximacion_inicial" xyz="0:0:30" angles="0:1.57:0" angles_type="ZYZ"/>
<TOPOINT name="G2_punto_inicial" xyz="0:0:10" angles="0:1.57:0" angles_type="ZYZ"/>
<POLILINE name="polilineaG2">
	<LINE name="G2_linea1" xyz2="0:-50:10" angles2="0:1.57:0" angles_type="ZYZ"/>
	<LINE name="G2_linea2" xyz2="200:-50:10" angles2="1:1:1" angles_type="ZYZ"/>
</POLILINE>
</GROUP>
</PROCESS>

=== arturosa67/XML_Definir_trayectorias_Robot/pruebas/pieza2_welding.xml
<?xml version="1.0" encoding="UTF-8"?>
<PROCESS type="welding MIG/MAG" units="mm:rad:s" HM_from_WORLD_to_SITE="[1 0 0 800;0 1 0 0;0 0 1 300;0 0 0 1]" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="fic_XSD.xsd">
<!--Part 2. Welding . KUKA KR16 -->
<GROUP name="Pieza2_Welding" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 -400;0 0 1 0;0 0 0 1]">
<TOPOINT name="inicio" xyz="217.39:0:200 " angles="0:-3.1416:0" angles_type="ZYZ"/>
<!--PASADA 1-->
<LINE name="p1" xyz2="217.39:0:10" angles2="0:-3.1416:0" angles_type="ZYZ"/>
<LINE name="p2" xyz2="217.39:800:10" angles2="0:-3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="p3" xyz="217.39:800:200" angles="0:-3.1416:0" angles_type="ZYZ"/>
<!--PASADA 2-->
<TOPOINT name="inicio" xyz="219.39:0:200 " angles="0:-3.1416:0" angles_type="ZYZ"/>
<LINE name="p4" xyz2="219.39:0:12" angles2="0:-3.1416:0" angles_type="ZYZ"/>
<LINE name="p5" xyz2="219.39:800:12" angles2="0:-3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="p6" xyz="219.39:800:200" angles="0:-3.1416:0" angles_type="ZYZ"/>
<!--PASADA 3-->
<TOPOINT name="inicio" xyz="215.39:0:200 " angles="0:-3.1416:0" angles_type="ZYZ"/>
<LINE name="p7" xyz2="215.39:0:12" angles2="0:-3.1416:0" angles_type="ZYZ"/>
<LINE name="p8" xyz2="215.39:800:12" angles2="0:-3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="p9" xyz="215.39:800:200" angles="0:-3.1416:0" angles_type="ZYZ"/>
</GROUP>
</PROCESS>

=== arturosa67/XML_Definir_trayectorias_Robot/pruebas/prueba_pieza1.xml
<?xml version="1.0" encoding="UTF-8"?>
<PROCESS type="welding MIG/MAG" units="mm:rad:s" HM_from_WORLD_to_SITE="[1 0 0 1000;0 1 0 0;0 0 1 0;0 0 0 1]" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="fic_XSD.xsd">

<!--esto es un comentario y se ignoran -->

<GROUP name="G1" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 0;0 0 1 500;0 0 0 1]">

<TOPOINT name="G1_punto_inicial" xyz="0:0:300 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="G1_punto_1" xyz="0:0:30" angles="0:3.1416:0" angles_type="ZYZ"/>
<!--<TOOL name="G1_activo_soldadura" velocity="1.2" time="0" active="on"/>-->
<LINE name="G1_linea_de_1_a_2" xyz2="70:0:30" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_2_a_3" xyz2="70:400:30" angles2="0:2.3562:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_3_a_4" xyz2="100:400:30" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_4_a_5" xyz2="100:0:30" angles2="0:3.927:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_5_a_6" xyz2="180:0:30" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_6_a_7" xyz2="180:0:0" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_7_a_8" xyz2="180:400:0" angles2="0:3.14:0" angles_type="ZYZ"/>
<TOPOINT name="vuelta_G1_punto_inicial_1" xyz="180:400:300" angles="0:3.14:0" angles_type="ZYZ"/>
<TOPOINT name="vuelta_G1_punto_inicial_2" xyz="0:0:300" angles="0:3.14:0" angles_type="ZYZ"/>
</GROUP>

</PROCESS>

=== arturosa67/XML_Definir_trayectorias_Robot/pruebas/prueba-cubo.xml
<?xml version="1.0" encoding="UTF-8"?>
<PROCESS type="welding MIG/MAG" units="mm:rad:s" HM_from_WORLD_to_SITE="[1 0 0 1000;0 1 0 0;0 0 1 500;0 0 0 1]" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="fic_XSD.xsd">

<!--esto es un comentario y se ignoran -->

<GROUP name="G1" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]">

<TOPOINT name="G1_punto_inicial" xyz="0:0:50 " angles="0:3.1416:0" angles_type="ZYZ"/>
<TOPOINT name="G1_punto_1" xyz="-250:-250:0 " angles="0:3.1416:0" angles_type="ZYZ"/>
<!--<TOOL name="G1_activo_soldadura" velocity="1.2" time="0" active="on"/>-->
<LINE name="G1_linea_de_1_a_2" xyz2="250:-250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_2_a_3" xyz2="250:250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_3_a_4" xyz2="-250:250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
<LINE name="G1_linea_de_4_a_1" xyz2="-250:-250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
<TOOL name="G1_desactivo_soldadura" velocity="1.2" time="0" active="off"/>
<TOPOINT name="vuelta_G1_punto_inicial" xyz="0:0:50 " angles="0:3.14:0" angles_type="ZYZ"/>
</GROUP>

<GROUP name="G2" HM_from_SITE_to_PART="[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]">
<TOPOINT name="G2_aproximacion_inicial" xyz="0:0:50 " angles="0:3.14:0" angles_type="ZYZ"/>
<TOPOINT name="G2_punto_inicial" xyz="-250:-250:0" angles="0:3.14:0" angles_type="ZYZ"/>
<POLILINE name="polilineaG2">
	<LINE name="G2_linea1" xyz2="250:-250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
	<LINE name="G2_linea2" xyz2="250:250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
        <LINE name="G2_linea2" xyz2="-250:250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
        <LINE name="G2_linea2" xyz2="-250:-250:0" angles2="0:3.14:0" angles_type="ZYZ"/>
</POLILINE>
</GROUP> 
</PROCESS>
